// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3113ef54DecodeGithubComBirrosWazeroDemoSumModel(in *jlexer.Lexer, out *Animal) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Name":
			out.Name = string(in.String())
		case "Order":
			out.Order = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3113ef54EncodeGithubComBirrosWazeroDemoSumModel(out *jwriter.Writer, in Animal) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"Order\":"
		out.RawString(prefix)
		out.String(string(in.Order))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Animal) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3113ef54EncodeGithubComBirrosWazeroDemoSumModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Animal) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3113ef54EncodeGithubComBirrosWazeroDemoSumModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Animal) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3113ef54DecodeGithubComBirrosWazeroDemoSumModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Animal) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3113ef54DecodeGithubComBirrosWazeroDemoSumModel(l, v)
}
